version: '3.9'
services:
  opkg-server-external-packages:
    image: ghcr.io/nimarty/hackypackages-server:${VERSION_TAG}
    volumes:
      - ${PACKAGE_DIR}:/packages
    command: 
      - develop
    ports:
      - ${PORT}:80
    restart: always
    profiles:
      - external
  opkg-server-internal-packages:
    image: ghcr.io/nimarty/hackypackages-server:${VERSION_TAG}
    ports:
      - ${PORT}:80
    restart: always
    profiles:
      - internal
