# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 1 * *' # at 00:00 on the first day of the month

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Bitbake Output
        id: cache-bitbake
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-bitbake-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bitbake-

      - name: Bitbake
        shell: bash
        run: |
          bash setup.sh
          source poky/oe-init-build-env
          bitbake hackypi-image

      - name: Remove Old Artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'

      - name: Archive New Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hackypi-image
          path: |
            build/tmp/deploy/images/raspberrypi4/hackypi-image-raspberrypi4-*.rpi-sdimg
