# Build and store HackyPi artifacts

name: Build

on:
  schedule:
    - cron: '0 0 1 * *' # at 00:00 on the first day of the month

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Bitbake Output
        id: cache-bitbake
        uses: actions/cache@v3
        with:
          path: build/downloads
          key: ${{ runner.os }}-bitbake-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bitbake-

      - name: Setup Environment
        shell: bash
        run: |
          bash setup.sh

      - name: Bitbake HackyPi Image - Raspberry Pi 4
        shell: bash
        run: |
          source poky/oe-init-build-env &>/dev/null
          bitbake hackypi-image

      - name: Bitbake HackyPi Image - Raspberry Pi 3
        shell: bash
        run: |
          source poky/oe-init-build-env &>/dev/null
          MACHINE=raspberrypi3 bitbake hackypi-image

      - name: Bitbake HackyPi Challenges
        shell: bash
        run: |
          source poky/oe-init-build-env &>/dev/null
          bitbake chatty-charly
          bitbake relaxed-rachel

      - name: Archive New Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: security-challenge-package
          path: |
            build/tmp/deploy/images/raspberrypi4/hackypi-image-raspberrypi4-*.rpi-sdimg
            build/tmp/deploy/images/raspberrypi3/hackypi-image-raspberrypi3-*.rpi-sdimg
            build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-dbg*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-src*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-doc*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-dev*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-ptest*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-syslog*.ipk
            !build/tmp/deploy/ipk/cortexa7t2hf-neon-vfpv4/*-staticdev*.ipk
